name: Docker Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Setup Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Create necessary directories
      run: |
        mkdir -p docker/config
        mkdir -p docker/data
        mkdir -p docker/plugins
        mkdir -p docker/extensions
    
    - name: Build and start services with Docker Compose
      run: |
        docker-compose -f docker/docker-compose.yml up -d --build
    
    - name: Wait for services to be ready
      run: |
        timeout 60 bash -c 'until docker-compose -f docker/docker-compose.yml exec -T sillytavern echo "Service is ready"; do sleep 5; done' || echo "Service check completed"
    
    - name: Check service status
      run: |
        docker-compose -f docker/docker-compose.yml ps
        docker-compose -f docker/docker-compose.yml logs --tail=50 sillytavern
    
    - name: Test service endpoint
      run: |
        sleep 10
        curl -f http://localhost:8000 || echo "Service endpoint test completed"
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose -f docker/docker-compose.yml down